spring:

  dubbo:
    appname: goods
    registry: zookeeper://127.0.0.1:2181
    protocol: dubbo
    port: 20883


  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: org.postgresql.Driver
      druid:
        url: jdbc:postgresql://egan.online:5432/aumalls?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
        username: postgres
        password: 123456
        initial-size: 1
        min-idle: 1
        max-active: 3
        max-wait: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          login-username: admin
          login-password: admin
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 2000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true

  redis:
    database: 0
    host: egan.online
    port: 19459
    password: 2016CUITBlogSystem
    timeout: 5s
    lettuce:
      pool:
        min-idle: 2
        max-active: 8
        max-idle: 4
  cloud:
    consul:
      discovery:
        service-name: goods
        instance-id: goods
        port: ${server.port}
      config:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.mall.goods.dao: debug

swagger: true