spring:

  dubbo:

    appname: consumer
    registry: zookeeper://127.0.0.1:2181
    protocol: dubbo
    port: 20880


  redis:
    database: 0
    host: egan.online
    port: 19459
    password: 2016CUITBlogSystem
    timeout: 5s
    lettuce:
      pool:
        min-idle: 2
        max-active: 8
        max-idle: 4
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/view
#      suffix: .jsp


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.mall.consumer.auth: debug
